language: cpp
sudo: false

branches:
  only:
  - master
  - "/^v\\d+\\./"

compiler:
  - gcc
  - clang

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
  
    # Boost
    - BOOST_VERSION=default

before_install:
  - pip install --user cpp-coveralls
 
script:
  - mkdir _builds
  - cd _builds
  - cmake -DVIA_HTTPLIB_BUILD_TESTS=ON ..
  - make

after_success:
  - coveralls --exclude lib --exclude unit_tests --gcov-options '\-lp'
  
notifications:
  email:
    recipients:
      - ken.barker@via-technology.aero
    on_success: change
    on_failure: always
    