language: cpp
os: linux
dist: bionic
sudo: false

branches:
  only:
  - master
  - develop

env:
  global:
    # Boost
    - BOOST_DIR=/usr/include
    - BOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu
    # CMake
    - CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR} -DBOOST_LIBRARYDIR=${BOOST_LIBRARYDIR}"
    
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
        - ln -s /usr/bin/g++-9 /usr/local/bin/g++
        - export CC=/usr/bin/gcc-9
        - export CXX=/usr/bin/g++-9
      
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - cmake
            - clang-8
            - libstdc++-8-dev
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - ln -s /usr/bin/clang-8 /usr/local/bin/gcc
        - ln -s /usr/bin/clang++-8 /usr/local/bin/g++
        - export CC=/usr/bin/clang-8
        - export CXX=/usr/bin/clang++-8
   
before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls
  
install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir _builds
  - cd _builds
  - cmake --version
  - cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} \
     -DVIA_HTTPLIB_BUILD_TESTS=ON -DVIA_HTTPLIB_COVERAGE=ON ${CMAKE_OPTIONS} .. 
  - make
  - ./via-httplib_test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls --root . -e build/CMakeFiles -E "test_*.o" --gcov-options '\-lp'
  
notifications:
  email:
    recipients:
      - ken.barker@via-technology.aero
    on_success: change
    on_failure: always
    