language: cpp
os: linux
dist: xenial
sudo: false

branches:
  only:
  - master
  - develop
  - "/^v\\d+\\./"

compiler:
  - gcc
  - clang

env:
  global:
    # Boost
    - BOOST_DIR=/usr/include
    - BOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu
    # CMake
    - CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR} -DBOOST_LIBRARYDIR=${BOOST_LIBRARYDIR}"
   
before_install:
  - pip install --user cpp-coveralls
  
install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
      
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir _builds
  - cd _builds
  - cmake -DVIA_HTTPLIB_BUILD_TESTS=ON -DVIA_HTTPLIB_COVERAGE=ON ${CMAKE_OPTIONS} .. 
  - make
  - ./via-httplib_test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls --root . -e build/CMakeFiles -E "test_*.o" --gcov-options '\-lp'
  
notifications:
  email:
    recipients:
      - ken.barker@via-technology.aero
    on_success: change
    on_failure: always
    